name: Build LaTeX PDFs

permissions:
  contents: write

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile Spanish CV
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: Compile English Resume
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex

      - name: Create / Update Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Resume
          files: |
            main.pdf
            resume.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
